---
name: test-workflow

on:
  push:
    branches: [master]
    paths:
      - .github/workflows/test-workflow.yml
  workflow_dispatch:
    branches: [master]

jobs:
  simple_test:
    runs-on: ubuntu-22.04
    steps:

      - name: start
        run: echo "Running test workflow. Be patient. 🐢"

      - name: test before checkout
        run: |
          pwd
          ls -la

      - name: Checkout code ✅
        uses: actions/checkout@v4

      - name: test after checkout
        run: |
          pwd
          ls -la
          echo "My repository: ${{ github.repository }}"
          echo "My branch: ${{ github.ref_name }}"
          echo "My Github username: ${{ github.actor }}"
